# Site settings
title: Jacy's Blog
description: Experience,Technology,Pits,Solution|Code!
# baseurl: "/particle" # the subpath of your site, e.g. /blog
# url: "localhost:3000" # the base hostname & protocol for your site e.g. http://willianjusten.com.br

# User settings
username: Jacy Liang
user_description: Fix Bugs、Play PingPong or badminton、2(you know)
user_title: Java Engineer
email: jacy8013@gmail.com
twitter_username: Jacy8013
github_username:  Jacy8013
gplus_username:  Jacy8013
facebook_username:  Jacy8013

# Google-analytics
google-analytics:
  id: ""

exclude: ['package.json', 'src' , 'node_modules']
